% -------------------------------------------------------------------
%  Generated by MATLAB on 20-Apr-2022 17:50:02
%  MATLAB version: 9.9.0.1538559 (R2020b) Update 3
% -------------------------------------------------------------------
                               

ssh2_conn = struct;
ssh2_conn.ganymed_java_library = ['/Users/Florian/Documents/MATLAB/Pico' ...
                                  'sec/RemoteControl/ssh2_v2_m1_r7/ssh2' ...
                                  '_v2_m1_r7/ganymed-ssh2-m1'];
ssh2_conn.ganymed_java_library_zip = ...
  ['/Users/Florian/Documents/MATLAB/Picosec/RemoteControl/ssh2_v2_m1_r7' ...
   '/ssh2_v2_m1_r7/ganymed-ssh2-m1.zip'];
ssh2_conn.ganymed_java_library_jar = ...
  ['/Users/Florian/Documents/MATLAB/Picosec/RemoteControl/ssh2_v2_m1_r7' ...
   '/ssh2_v2_m1_r7/ganymed-ssh2-m1.jar'];
ssh2_conn.ganymed_java_library_jar_path = ...
  ['/Users/Florian/Documents/MATLAB/Picosec/RemoteControl/ssh2_v2_m1_r7' ...
   '/ssh2_v2_m1_r7/ganymed-ssh2-m1/ganymed-ssh2-m1.jar'];
ssh2_conn.hostname = '128.141.221.114';
ssh2_conn.username = 'GDD';
ssh2_conn.password = 'Win_Admin';
ssh2_conn.port = 22;
ssh2_conn.connection = [];
ssh2_conn.authenticated = 0;
ssh2_conn.autoreconnect = 0;
ssh2_conn.close_connection = 0;
ssh2_conn.pem_file = [];
ssh2_conn.pem_private_key = [];
ssh2_conn.pem_private_key_password = [];
ssh2_conn.command = [];
ssh2_conn.command_session = [];
ssh2_conn.command_ignore_response = 0;
ssh2_conn.command_result = [];
ssh2_conn.sftp = 0;
ssh2_conn.scp = 0;
ssh2_conn.sendfiles = 0;
ssh2_conn.getfiles = 0;
ssh2_conn.remote_file = [];
ssh2_conn.local_target_direcory = [];
ssh2_conn.local_file = [];
ssh2_conn.remote_target_direcory = [];
ssh2_conn.remote_file_new_name = [];
ssh2_conn.remote_file_mode = 600;
ssh2_conn.verified_config = 0;
ssh2_conn.ssh2_java_library_loaded = 1;

